# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vote',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='\u0413\u043e\u043b\u043e\u0441\u043e\u0432'),
        ),
    ]
