# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('accounts', '0002_auto_20160329_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='programming_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_languages', to='blog.ProgrammingLang', verbose_name=''),
            preserve_default=False,
        ),
    ]
