# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_programming_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='programming_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_languages', to='blog.ProgrammingLang', verbose_name=''),
        ),
    ]
