# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_subcategory'),
        ('accounts', '0004_auto_20160329_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='programming_language',
        ),
        migrations.AddField(
            model_name='user',
            name='programming_language',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_languages', to='blog.ProgrammingLang', verbose_name=''),
        ),
    ]
