# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160329_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u0417\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
