# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='programming_language',
        ),
    ]
