# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_programming_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u0418\u043c\u044f \u043f\u043e\u0447\u0442\u044b'),
        ),
    ]
