# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('tags', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('good_vote', models.PositiveIntegerField(verbose_name='\u0425\u043e\u0440\u043e\u0448\u0438\u0439 \u0433\u043e\u043b\u043e\u0441')),
                ('bad_vote', models.PositiveIntegerField(verbose_name='\u041f\u043b\u043e\u0445\u043e\u0439 \u0433\u043e\u043b\u043e\u0441')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('public', models.BooleanField(default=True, verbose_name='\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u044f')),
                ('moderated', models.BooleanField(default=False, verbose_name='\u0416\u0430\u043b\u043e\u0431\u0430')),
                ('count_post', models.PositiveIntegerField(verbose_name='\u041f\u043e\u0441\u0442\u043e\u0432')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_subcategory', to='blog.Subcategory', verbose_name='\u041f\u043e\u0434\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_user', to=settings.AUTH_USER_MODEL, verbose_name='\u042e\u0437\u0435\u0440')),
            ],
            options={
                'verbose_name': '\u0422\u043e\u043f\u0438\u043a',
                'verbose_name_plural': '\u0422\u043e\u043f\u0438\u043a\u0438',
            },
        ),
    ]
