# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='programming_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='blog.ProgrammingLang', verbose_name='\u042f\u0437\u044b\u043a'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='bad_vote',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='\u041f\u043b\u043e\u0445\u043e\u0439 \u0433\u043e\u043b\u043e\u0441'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='count_post',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='\u041f\u043e\u0441\u0442\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='good_vote',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='\u0425\u043e\u0440\u043e\u0448\u0438\u0439 \u0433\u043e\u043b\u043e\u0441'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='tags',
            field=models.CharField(max_length=256, verbose_name='\u0422\u0435\u0433\u0438'),
        ),
    ]
