# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20160331_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_vote', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u0425\u043e\u0440\u043e\u0448\u0438\u0439 \u0433\u043e\u043b\u043e\u0441')),
                ('bad_vote', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u041f\u043b\u043e\u0445\u043e\u0439 \u0433\u043e\u043b\u043e\u0441')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='bad_vote',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='good_vote',
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(verbose_name='\u041f\u043e\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='vote',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='blog.Topic', verbose_name='\u0422\u043e\u043f\u0438\u043a'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_user', to=settings.AUTH_USER_MODEL, verbose_name='\u042e\u0437\u0435\u0440'),
        ),
    ]
