# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160401_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='bad_vote',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='\u041f\u043b\u043e\u0445\u043e\u0439 \u0433\u043e\u043b\u043e\u0441'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='good_vote',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='\u0425\u043e\u0440\u043e\u0448\u0438\u0439 \u0433\u043e\u043b\u043e\u0441'),
        ),
    ]
