# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20160401_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalmessage_votes', to='blog.Topic', verbose_name='\u0422\u043e\u043f\u0438\u043a')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalmessage_user', to=settings.AUTH_USER_MODEL, verbose_name='\u042e\u0437\u0435\u0440')),
            ],
        ),
    ]
