# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160402_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmessage',
            name='new',
            field=models.BooleanField(default=True, verbose_name='\u041d\u043e\u0432\u043e\u0435'),
        ),
        migrations.AddField(
            model_name='personalmessage',
            name='trash',
            field=models.BooleanField(default=False, verbose_name='\u041c\u0443\u0441\u043e\u0440\u043a\u0430'),
        ),
    ]
