# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160402_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalmessage',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalmessage_votes', to='blog.Topic', verbose_name='\u0422\u043e\u043f\u0438\u043a'),
        ),
    ]
