# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_remove_personalmessage_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmessage',
            name='recipient',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipient', to=settings.AUTH_USER_MODEL, verbose_name='\u042e\u0437\u0435\u0440 \u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044c'),
        ),
    ]
