# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 14:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_personalmessage_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalmessage',
            name='recipient',
        ),
        migrations.AddField(
            model_name='personalmessage',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL, verbose_name='\u042e\u0437\u0435\u0440 \u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044c'),
        ),
    ]
