# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_topic_count_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='count_views',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432'),
        ),
    ]
