# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0019_auto_20160406_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='\u041f\u0440\u043e\u0431\u043b\u0435\u043c\u0430')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('moderated', models.BooleanField(default=True, verbose_name='\u041f\u0440\u043e\u0432\u0435\u0440\u0438\u043b \u043c\u043e\u0434\u0435\u0440\u0430\u0442\u043e\u0440')),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='moderated',
        ),
        migrations.AddField(
            model_name='moderated',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_moderated', to='blog.Topic', verbose_name='\u0422\u043e\u043f\u0438\u043a'),
        ),
        migrations.AddField(
            model_name='moderated',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderated_user', to=settings.AUTH_USER_MODEL, verbose_name='\u042e\u0437\u0435\u0440'),
        ),
    ]
