# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20160408_1219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalMessage',
            new_name='TopicMessage',
        ),
    ]
