# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20160409_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicmessage',
            name='new',
        ),
        migrations.RemoveField(
            model_name='topicmessage',
            name='trash',
        ),
        migrations.AddField(
            model_name='topicmessage',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='\u0423\u0434\u0430\u043b\u0435\u043d\u0438\u0435 \u044e\u0437\u0435\u0440'),
        ),
        migrations.AddField(
            model_name='topicmessage',
            name='delete_recipient',
            field=models.BooleanField(default=False, verbose_name='\u0423\u0434\u0430\u043b\u0435\u043d\u0438\u0435 \u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='topicmessage',
            name='theme',
            field=models.CharField(default=1, max_length=500, verbose_name=''),
            preserve_default=False,
        ),
    ]
