# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20160409_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgrammingLang',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='topicmessage',
            options={'verbose_name': '\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435', 'verbose_name_plural': '\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f'},
        ),
    ]
