# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20160412_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='programming_language',
            new_name='category',
        ),
    ]
