# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20160414_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=35)),
                ('slug', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='tags',
        ),
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(related_name='topic_tags', to='blog.Tag', verbose_name='\u0422\u044d\u0433\u0438'),
        ),
    ]
